version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: nginx-web
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  php:
    image: php:8.3-fpm
    container_name: php-fpm
    volumes:
      - ./app:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge